apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: erp-financial-services
  labels:
    app: kafka
    version: v1
    component: infra
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
