apiVersion: v1
kind: Service
metadata:
  name: budget-service
  namespace: erp-financial-services
  labels:
    app: budget-service
    version: v1
    component: business
spec:
  type: ClusterIP
  selector:
    app: budget-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
