apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: erp-financial-services
  labels:
    app: transaction-service
    version: v1
    component: business
spec:
  type: ClusterIP
  selector:
    app: transaction-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
