apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: erp-financial-services
  labels:
    app: postgres
    version: v1
    component: infra
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
