input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service] {
    mutate {
      add_field => { "[@metadata][index_prefix]" => "%{service}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "erp-%{[service]}-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
