server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb?TimeZone=UTC

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - feign.FeignException$NotFound
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
  retry:
    instances:
      accountService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - feign.FeignException$NotFound
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
  ratelimiter:
    instances:
      accountService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
