server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb?TimeZone=UTC

resilience4j:
  ratelimiter:
    instances:
      login:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0s
