apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: erp-financial-services
  labels:
    app: account-service
    version: v1
    component: business
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
